[build]
  publish = "/"
  command = "# No build command"

# Handle form submissions
[[redirects]]
  from = "/success"
  to = "/index.html"
  status = 200

# SPA redirect - make sure this ALWAYS comes last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
